name: clutch
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
  # sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.2
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.1
  dio: ^5.7.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  # flutter_inappwebview: ^6.1.5
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_stripe:
  flutter_paypal_checkout:
  razorpay_flutter: ^1.3.5
  flutter_paystack: ^1.0.7
  # flutter_stripe: ^11.4.0
  # flutter_paypal_checkout: ^1.0.1
  # razorpay_flutter: ^1.3.5

  # flutter_stripe: ^11.4.0
  flutter_widget_from_html: ^0.9.1
  fluttertoast: ^8.2.10
  flutterwave_standard: ^1.0.7
  # flutterwave_standard: ^1.0.8
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  image_picker: ^1.1.2
  # intl: ^0.19.0
  intl: ^0.17.0
  logger: ^2.5.0
  lottie: ^3.0.0
  monnify_flutter_sdk_plus: ^1.1.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  paytm_allinonesdk: ^1.2.8
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.5.0
  qr_flutter: ^4.1.0
  rename_app: ^1.6.2
  shared_preferences: ^2.3.5
  upgrader: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # dependency_overrides:

dependency_overrides:
  intl: "0.17.0"
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# -dontshrink
# -dontobfuscate
# -dontoptimize
